<?php

/**
 * @file
 * Settings for the zoetrope_image commerce migration.
 */

/**
 * Implements hook_migrate_api().
 *
 * You must implement hook_migrate_api(), setting the API level to 2, for
 * your migration classes to be recognized by the Migrate module.
 */
function zoetrope_viewer_migrate_commerce_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_menu().
 */
function zoetrope_viewer_migrate_commerce_menu() {
  $menu = array();

  $menu['admin/content/zoetrope_commerce'] = array(
    'title' => "Zoetrope commerce migration settings",
    'access arguments' => array("administer site configuration"),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zoetrope_viewer_migrate_commerce_settings_form'),
    'file' => FALSE,
  );

  return $menu;
}

/**
 * Implements hook_form().
 */
function zoetrope_viewer_migrate_commerce_settings_form($form, $form_state) {

  // The Feed URL which will be used to populate the field.
  $form['zoetrope_viewer_migrate_commerce:source_url'] = array(
    '#title' => 'Zoetrope Feed URL',
    '#decription' => 'The feed url can be fetched from your Zoetrope user area, by logging in and going ' .
    'to http://zoetrope.io/user, then clicking on "feeds". Select a drupal feed type and paste it here.',
    '#type' => 'textfield',
    '#default_value' => variable_get('zoetrope_viewer_migrate_commerce:source_url', ''),
    '#max_length' => 500,
  );

  // The zoetrope field to import to (has to be on an commerce product bundle).
  $bundles = field_info_instances('commerce_product');
  $options = array();
  foreach($bundles as $bundle => $fields_info){
    foreach ($fields_info as $field_name => $field_instance) {
      $field_info = field_info_field($field_name);
      if ($field_info['type'] == 'zoetrope_uuid_field') {
        $options[$field_name] = $field_instance['label'];
      }
    }
  }

  $form['zoetrope_viewer_migrate_commerce:dest_field'] = array(
    '#title' => 'Zoetrope Field to import to',
    '#description' => 'Normally you would only have one image per product field',
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => NULL,
  );

  if (count($options) == 0) {
    drupal_set_message('You need to add a `zoetrope_image` field to a commerce product first.', 'error');
    $form['zoetrope_viewer_migrate_commerce:dest_field']['#disabled'] = TRUE;
  }

  return system_settings_form($form);
}
