<?php

/**
 * @file
 * Zoetrope Ltd. 2014
 *
 * Adds a UUID field type and field formatters to display zoetrope
 * engage&trade; images in a drupal site
 *
 */

/**
 * This constant is the zoetrope CDN url, do not change here, there's a
 * settings page to override it.
 */
const ZOETROPE_VIEWER_CDN = '//d34tuy4jppw3dn.cloudfront.net';

/**
 * Implements hook_permission
 */
function zoetrope_viewer_permission(){
  return array(
    'administer zoetrope viewer' => array(
      'title' => t('Administer Zoetrope Viewer Settings'),
      'restrict access' => TRUE,
    )
  );
}

/**
 * Implements hook_menu().
 */
function zoetrope_viewer_menu() {
  $menu['admin/config/media/zoetrope_viewer'] = array(
    'title' => t('Zoetrope Viewer Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zoetrope_viewer_settings_form'),
    'access arguments' => array('administer zoetrope viewer')
  );
  return $menu;
}

/**
 * Implements hook_form().
 */
function zoetrope_viewer_settings_form($form, &$form_state) {

  $form['custom_cdn'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use custom CDN'),
    '#description' => t('Normally your images will be hosted by Zoetrope,' .
      ' we will tell you if you need this.'),
    '#default_value' => (variable_get('zoetrope_viewer:cdn', FALSE)) ? 1 : 0,
  );

  $form['cdn_url'] = array(
    '#type' => 'textfield',
    '#title' => t('base URL'),
    '#description' => t('The CDN url with no http:// or https://'),
    '#default_value' => variable_get('zoetrope_viewer:cdn', FALSE),
    '#states' => array(
      'visible' => array(
        ':input[name="custom_cdn"]' => array('checked' => TRUE),
      ),
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Validation for CDN urls
 */
function zoetrope_viewer_settings_form_validate($form, &$form_state) {
  $values = $form_state['values'];
  if($values['custom_cdn']) {
    if(!valid_url($values['cdn_url'])){
      form_set_error('cdn_url', t('The CDN url does not appear to be a valid url.'));
    }
  }
}

/**
 * Implements hook_form_submit().
 */
function zoetrope_viewer_settings_form_submit($form, &$form_state) {
  $values = $form_state['values'];
  if($values['custom_cdn']) {
    $zoe_cdn = $values['cdn_url'];
  }
  else {
    // default zoetrope CDN
    $zoe_cdn = FALSE;
  }
  variable_set('zoetrope_viewer:cdn', $zoe_cdn);
}

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function zoetrope_viewer_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'zoetrope_uuid_field' => array(
      'label' => t('Zoetrope ID'),
      'description' => t('Add a Zoetrope Engage&trade; image to an entity'),
      'default_widget' => 'zoetrope_uuid_field_text_widget',
      'default_formatter' => 'zoetrope_engage_image',
      'property_type' => 'zoetrope_uuid_field',
      'property_callbacks' => array('zoetrope_viewer_uuid_field_property_info_callback')
    ),
  );
}

/**
 * Callback to alter the property info of Dimensions fields.
 *
 * @see physical_field_info().
 */
function zoetrope_viewer_uuid_field_property_info_callback(&$info, $entity_type, $field, $instance, $field_type) {
  $name = $field['field_name'];
  $property = &$info[$entity_type]['bundles'][$instance['bundle']]['properties'][$name];

  $property['type'] = ($field['cardinality'] != 1) ? 'list<zoetrope_uuid_field>' : 'zoetrope_uuid_field';
  $property['getter callback'] = 'entity_metadata_field_verbatim_get';
  $property['setter callback'] = 'entity_metadata_field_verbatim_set';
  $property['auto creation'] = 'zoetrope_viewer_uuid_field_field_data_auto_creation';
  $property['property info'] = zoetrope_viewer_uuid_field_field_data_property_info();

  unset($property['query callback']);
}

/**
 * Returns the default array structure for a Dimensions field for use when
 * creating new data arrays through an entity metadata wrapper.
 */
function zoetrope_viewer_uuid_field_field_data_auto_creation() {
  return array('zoetrope_uuid' => '', 'start_position' => 0, 'gallery_image_positions' => array());
}

/**
 * Defines info for the properties of the Dimensions field data structure.
 */
function zoetrope_viewer_uuid_field_field_data_property_info($name = NULL) {
  return array(
    'zoetrope_uuid' => array(
      'label' => t('Zoetrope ID'),
      'description' => t('The Zoetrope ID for the image.'),
      'type' => 'text',
      'getter callback' => 'entity_property_verbatim_get',
      'setter callback '=> 'entity_property_verbatim_set',
    ),
    'start_position' => array(
      'label' => t('Starting Position'),
      'description' => t('The index of the initial view.'),
      'type' => 'integer',
      'getter callback' => 'entity_property_verbatim_get',
      'setter callback' => 'entity_property_verbatim_set',
    ),
    'gallery_image_positions' => array(
      'label' => t('Gallery Image Positions'),
      'description' => t('Holds information about the positions and priorities of images to be used for 2D gallery scenarios.'),
      'type' => 'struct',
      'getter callback' => 'entity_property_verbatim_get',
      'setter callback' => 'entity_property_verbatim_set',
    ),
  );
}

/**
 * Implements hook_field_presave().
 *
 * gallery_image_positions needs to be serialized here
 */
function zoetrope_viewer_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items){
  foreach($items as &$item){
    if(isset($item['gallery_image_positions'])){
      $item['gallery_image_positions'] = serialize($item['gallery_image_positions']);
    }
  }
}

/**
 * Implements hook_field_load().
 */
function zoetrope_viewer_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age){
  foreach($items as &$entity){
    foreach ($entity as &$item) {
      if(isset($item['gallery_image_positions'])){
        $item['gallery_image_positions'] = unserialize($item['gallery_image_positions']);
      }
    }
  }
}

/**
 * Implements hook_field_validate().
 */
function zoetrope_viewer_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    if (!empty($item['zoetrope_uuid'])) {
      $uuid_valid = TRUE;
      // Test for valid UUID (mongo ObjectID style UUID).
      if (!preg_match("/^[0-9a-fA-F]{24}$/", $item['zoetrope_uuid'])) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
          'error' => 'zoetrope_uuid_field_uuid_invalid',
          'message' => t('Zoetrope ID field must be a valid UUID.'),
        );
        $uuid_valid = FALSE;
      }
      // Make a request to check it is infact a working image.
      /*if ($uuid_valid) {
        $url = zoetrope_viewer_preview_image_url($item['zoetrope_uuid']);
        $result = drupal_http_request($url);
        if ($result->code !== '200') {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'zoetrope_uuid_field_uuid_invalid',
            'message' => t('The Zoetrope ID does not seem to point to an image.'),
          );
        }
      }*/

      if (!empty($item['start_position'])) {
        $value = $item['start_position'];
        if (!is_numeric($value) || intval($value) != $value || (intval($value) < 0) || (intval($value) > 107)) {
          $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'zoetrope_uuid_field_start_position_invalid',
            'message' => t('The starting position needs to be an integer between 0-107.'),
          );
        }
      }
    }

    //TODO: add validation of gallery_image_positions
  }
}

/**
 * Implements hook_field_widget_info().
 *
 * Only widget is a text input box.
 */
function zoetrope_viewer_field_widget_info() {
  return array(
    'zoetrope_uuid_field_text_widget' => array(
      'label' => t('Zoetrope Text Field'),
      'field types' => array('zoetrope_uuid_field'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 *
 * This implements our input box as defined in hook_field_widget_info().
 */
function zoetrope_viewer_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  $uuid = isset($items[$delta]['zoetrope_uuid']) ?
    $items[$delta]['zoetrope_uuid'] : '';

  $start_position = isset($items[$delta]['start_position']) ?
    $items[$delta]['start_position'] : '0';

  $widget = &$element;
  $widget['#delta'] = $delta;
  switch ($instance['widget']['type']) {
    case 'zoetrope_uuid_field_text_widget':
      $widget += array(
        '#type' => 'fieldset',
        '#title' => t('Zoetrope Image'),
        '#attached' => array(
          'css' => array(drupal_get_path('module','zoetrope_viewer') . '/css/zoetrope_viewer_admin.css'),
        )
      );

      $widget['zoetrope_uuid'] = array(
        '#title' => t('Zoetrope ID'),
        '#type' => 'textfield',
        '#default_value' => $uuid,
        '#size' => 40,
        '#maxlength' => 40,
        '#attributes' => array(
          'class' => array('zoetrope-uuid-field-zoetrope-id'),
        )
      );
      $widget['start_position'] = array(
        '#title' => t('Start position'),
        '#type' => 'textfield',
        '#default_value' => $start_position,
        '#size' => 3,
        '#maxlength' => 3,
        '#attributes' => array(
          'class' => array('zoetrope-uuid-field-starting-position'),
        )
      );
      break;
  }
  return $element;
}

/**
 * Implements hook_field_widget_error().
 */
function zoetrope_viewer_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'zoetrope_uuid_field_uuid_invalid':
      form_error($element['zoetrope_uuid'], $error['message']);
      break;
    case 'zoetrope_uuid_field_start_position_invalid':
      form_error($element['start_position'], $error['message']);
      break;
  }
}


/**
 * Implements hook_field_is_empty().
 */
function zoetrope_viewer_field_is_empty($item, $field) {
  return empty($item['zoetrope_uuid']);
}

/**
 * Implements hook_field_formatter_info().
 */
function zoetrope_viewer_field_formatter_info() {
  $info = array(
    'zoetrope_engage_image' => array(
      'label' => t('Zoetrope Reel viewer'),
      'field types' => array('zoetrope_uuid_field', 'text'),
      'description' => t('Embeds the zoetrope viewer.'),
      'settings' => array(
        'inline_image' => FALSE,
        'force_mini' => FALSE,
        'trigger_image' => '',
        '2d_version' => FALSE,
        'image_style' => '',
        'loadspin' => FALSE,
        'idle-animate' => FALSE,
        'autoload' => FALSE,
        'preload' => FALSE,
        'show-cta' => FALSE,
      ),
    ),
    'zoetrope_image_gallery' => array(
      'label' => t('Image + Zoetrope Images'),
      'field types' => array('image'),
      'description' => t('Image formatter which includes zoetrope images.'),
      'settings' => array(
        'zoetrope_uuid_field_name' => '',
        'position' => 'first',
        'image_style' => '',
      ),
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function zoetrope_viewer_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  dsm($field);

  switch ($instance['display'][$view_mode]['type']) {

    case 'zoetrope_engage_image':

      $states_non_2d =  array(
        'visible' => array(
          ':input[name="fields['.$field['field_name'].'][settings_edit_form][settings][2d_version]"]' => array('checked' => FALSE),
        ),
      );

      $element['2d_version'] = array(
        '#type' => 'checkbox',
        '#title' => t('2D version'),
        '#description' => t('Forces the viewer to just show a 2D image.'),
        '#default_value' => $settings['2d_version'],
      );

      $element['inline_image'] = array(
        '#type' => t('checkbox'),
        '#title' => t('Inline Engage image'),
        '#description' => t('Inline images appear in the page content, whereas normal engage images open in a responsive lightbox overlay.'),
        '#default_value' => $settings['inline_image'],
        '#states' => $states_non_2d,
      );

      $element['force_mini'] = array(
        '#type' => 'checkbox',
        '#title' => t('Force Mini (Non inline only)'),
        '#description' => t('Forces the viewer to display a mini zoetrope viewer, rather than the responsive one in the interest of bandwidth.'),
        '#default_value' => $settings['force_mini'],
        '#states' => $states_non_2d,
      );

      $element['loadspin'] = array(
        '#type' => 'checkbox',
        '#title' => t('Spin once on load'),
        '#description' => t('Spins one time when loaded.'),
        '#default_value' => $settings['autospin'],
        '#states' => $states_non_2d,
      );

      $element['idle-animate'] = array(
        '#type' => 'checkbox',
        '#title' => t('Spin when Idle'),
        '#description' => t('Spins when not being dragged by the user.'),
        '#default_value' => $settings['idle-animate'],
        '#states' => $states_non_2d,
      );

      $element['show-cta'] = array(
        '#type' => 'checkbox',
        '#title' => t('Hide calls to action'),
        '#description' => t('Hides the labels which indcate the viewer is interactive.'),
        '#default_value' => $settings['show-cta'],
        '#states' => $states_non_2d,
      );

      $element['autoload'] = array(
        '#type' => 'checkbox',
        '#title' => t('Instant load'),
        '#description' => t('autoload on pageload.'),
        '#default_value' => $settings['autoload'],
        '#states' => $states_non_2d,
      );

      $element['preload'] = array(
        '#type' => 'checkbox',
        '#title' => t('Preload'),
        '#description' => t('Preload for extra responsiveness at the cost of server bandwidth'),
        '#default_value' => $settings['preload'],
        '#states' => $states_non_2d,
      );
      $element['preload']['#states']['visible'][':input[name="autoload"]'] = array('value' => FALSE);

      $fields_info = field_info_instances($instance['entity_type'], $instance['bundle']);
      $options = array();
      foreach ($fields_info as $field_name => $field_instance) {
        $field_info = field_info_field($field_name);
        if ($field_info['type'] == 'image') {
          $options[$field_name] = $field_instance['label'];
        }
      }

      $element['trigger_image'] = array(
        '#title' => t('Trigger Image Override field'),
        '#type' => 'select',
        '#description' => t('Select an image field to use as the trigger image if present.'),
        '#default_value' => $settings['trigger_image'],
        '#options' => $options,
        '#empty_option' => t('None, (Use initial Engage view).'),
      );

      $image_styles = image_style_options(FALSE, PASS_THROUGH);
      $element['image_style'] = array(
        '#title' => t('Image style'),
        '#type' => 'select',
        '#default_value' => $settings['image_style'],
        '#empty_option' => t('None (original image)'),
        '#options' => $image_styles,
      );
      break;

    case 'zoetrope_image_gallery':

      $fields_info = field_info_instances($instance['entity_type'], $instance['bundle']);
      $options = array('' => 'None');
      foreach ($fields_info as $field_name => $field_instance) {
        $field_info = field_info_field($field_name);
        if ($field_info['type'] == 'zoetrope_uuid_field') {
          $options[$field_name] = $field_instance['label'];
        }
      }

      $element['zoetrope_uuid_field_name'] = array(
        '#type' => 'select',
        '#title' => t('Zoetrope ID field to combine'),
        '#description' => t('The field on this entity to combine for display. You probably want to hide the zoetrope_uuid_field which you use here.'),
        '#default_value' => $settings['zoetrope_uuid_field_name'],
        '#options' => $options,
      );

      $element['position'] = array(
        '#type' => 'select',
        '#title' => t('Zoetrope positions'),
        '#description' => t('Where should the zoetrope images be placed'),
        '#default_value' => $settings['position'],
        '#options' => array(
          'start' => t('Start'),
          'end' => t('End'),
        ),
      );

      $image_styles = image_style_options(FALSE, PASS_THROUGH);
      $element['image_style'] = array(
        '#title' => t('Image style'),
        '#type' => 'select',
        '#default_value' => $settings['image_style'],
        '#empty_option' => t('None (original image)'),
        '#options' => $image_styles,
      );
      break;
  }
  return $element;

}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function zoetrope_viewer_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = array();
  switch ($display['type']) {
    case 'zoetrope_engage_image':
      $summary[] = $settings['inline_image'] ? t('Inline (no overlay)') : t('Show in Overlay');
      $summary[] = $settings['force_mini'] ? t('Mini Viewer') : t('Responsive Viewer');
      $summary[] = $settings['trigger_image'] ? t('Using field \'@field\' for the trigger image',
        array('@field' => $settings['trigger_image'])) : t('Zoetrope trigger image.');
      $image_styles = image_style_options(FALSE, PASS_THROUGH);
      // Unset possible 'No defined styles' option.
      unset($image_styles['']);
      if (isset($image_styles[$settings['image_style']])) {
        $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['image_style']]));
      }
      else {
        $summary[] = t('Original image');
      }
      break;

    case 'zoetrope_image_gallery':
      $image_styles = image_style_options(FALSE, PASS_THROUGH);
      // Unset possible 'No defined styles' option.
      unset($image_styles['']);
      if (isset($image_styles[$settings['image_style']])) {
        $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['image_style']]));
      }
      else {
        $summary[] = t('Original image');
      }
      if (empty($settings['zoetrope_uuid_field_name'])) {
        $summary[] = t('Engage Image configured');
      }
      else {
        $summary[] = t('Using field `@name` at the @pos of list.',
          array('@name' => $settings['zoetrope_uuid_field_name'], '@pos' => $settings['position']));
      }
      break;
  }
  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_prepare_view().
 */
function zoetrope_viewer_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items, $displays) {

  foreach ($entities as $id => $entity) {
    $instance = $instances[$id];
    $display = $displays[$id];
    // If it's a zoetrope_image_gallery display.
    if ($display['type'] == 'zoetrope_image_gallery' && !empty($display['settings']['zoetrope_uuid_field_name'])) {
      // Add the zoetrope engage images if we can.
      if (isset($entity->{$display['settings']['zoetrope_uuid_field_name']})) {
        $zoetrope_uuid_field = $entity->{$display['settings']['zoetrope_uuid_field_name']}[LANGUAGE_NONE];
        $e_items = &$items[$id];
        foreach ($zoetrope_uuid_field as $value) {
          if ($display['settings']['position'] == 'end') {
            array_push($e_items, $value);
          }
          else {
            array_unshift($e_items, $value);
          }
        }
      }
    }
    elseif ($display['type'] == 'zoetrope_engage_image' && !empty($display['settings']['trigger_image'])) {
      if (isset($entity->{$display['settings']['trigger_image']})) {
        $image_field = $entity->{$display['settings']['trigger_image']}[LANGUAGE_NONE];
        $e_items = &$items[$id];
        // Match up image field deltas with zoetrope image deltas
        foreach ($e_items as $delta => &$value) {
          $value['trigger_image'] = $image_field[$delta];
        }
      }
    }
  }
}

/**
 * Implements hook_field_formatter_view().
 */
function zoetrope_viewer_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();
  $settings = $display['settings'];
  $zoe_cdn = variable_get('zoetrope_viewer:cdn', ZOETROPE_VIEWER_CDN);
  drupal_add_js(ZOETROPE_VIEWER_CDN . '/v1/js/zoe-widget.min.js', array(
    'type' => 'external',
    'group' => JS_THEME,
    'weight' => 1000000,
    )
  );
  drupal_add_css(ZOETROPE_VIEWER_CDN . '/v1/css/style.css', 'external');

  foreach ($items as $delta => $item) {
    switch ($display['type']) {
      case 'zoetrope_engage_image':
        $element[$delta] = _zoetrope_viewer_engage_image_field_view($item, $settings, $instance['id']);
        break;

      case 'zoetrope_image_gallery':

        if (isset($item['zoetrope_uuid_field'])) {
          $element[$delta] = _zoetrope_viewer_engage_image_field_view($item, $settings);
        }
        else {
          $element[$delta] = array(
            '#theme' => 'image_formatter',
            '#item' => $item,
            '#image_style' => $display['settings']['image_style'],
            '#path' => '',
          );
        }
        break;

    }
  }
  return $element;
}

/**
 * Helper to make a renderable array.
 */
function _zoetrope_viewer_engage_image_field_view($item, $settings, $rel = FALSE) {
  $img_uuid = empty($item['zoetrope_uuid']) ? $item['value'] : $item['zoetrope_uuid'];
  $start_position = isset($item['start_position']) ?
    $item['start_position'] : 0;

  $site_uuid = variable_get('zoetrope_viewer:site_uuid', '');

  // Override sites default CDN (done by modules sometimes).
  $cdn = !empty($item['cdn']) ? $item['cdn'] : FALSE;
  $preview_path = _zoetrope_viewer_image_url($img_uuid,500,$start_position,$cdn);

  $e = array(
    '#theme' => 'image',
    '#path' => $preview_path,
    '#attributes' => array(
      'data-zoe-image' => $img_uuid,
      'data-zoe-site' => $site_uuid,
      'data-zoe-rel' => $rel,
      'data-zoe-start-ind' => $start_position,
    ),
  );

  // Force the size of the trigger image (depreciated).
  if (isset($settings['trigger_size']) && intval($settings['trigger_size']) !== 0) {
    $e['#attributes']['width'] = $settings['trigger_size'];
    $e['#attributes']['height'] = $settings['trigger_size'];
  }

  // Use the sizes from an image style for the trigger.
  if (!empty($settings['image_style'])) {
    $dimensions = array('width' => 500, 'height' => 500);
    image_style_transform_dimensions($settings['image_style'], $dimensions);
    $e['#attributes']['width'] = $dimensions['width'];
    $e['#attributes']['height'] = $dimensions['height'];
  }

  if(!isset($settings['2d_version']) || $settings['2d_version'] == FALSE ){
    $e['#attributes']['class'] = array('zoe-engage-image');
  }
  else{
    // we can quit here to keep the markup cleaner with attributes which wont be used
    return $e;
  }

  if($cdn){
    $e['#attributes']['data-zoe-cdn-override'] = $cdn;
  }

  // Alternate trigger image.
  if (isset($settings['trigger_image']) && !empty($item['trigger_image'])) {
    $e['#path'] = $item['trigger_image'];
    $e['#path'] = $item['trigger_image']['uri'];

    if (!empty($settings['image_style'])) {
      $e['#theme'] = 'image_style';
      $e['#style_name'] = $settings['image_style'];
    }
  }

  // Force the mini viewer.
  if (isset($settings['force_mini']) && $settings['force_mini']) {
    $e['#attributes']['class'][] = 'zoe-mini';
  }

  // Inline the viewer.
  if (isset($settings['inline_image']) && $settings['inline_image']) {
    $e['#attributes']['data-zoe-inline'] = '';
  }


  // Spin once on load
  if(!empty($settings['loadspin']) && $settings['loadspin']){
    $e['#attributes']['data-zoe-loadspin'] = '1';
  }

  // Animate 
  if(!empty($settings['auto-animate']) && $settings['auto-animate']){
    $e['#attributes']['data-zoe-auto-animate'] = '1';
  }

  //hide CTA
  if(!empty($settings['show-cta']) && $settings['show-cta']){
    $e['#attributes']['data-zoe-show-cta'] = '1';
  }

  //autoload
  if(!empty($settings['autoload']) && $settings['autoload']){
    $e['#attributes']['data-zoe-autoload'] = '1';
  }

  //preload
  if(!empty($settings['preload']) && $settings['preload']){
    $e['#attributes']['data-zoe-preload'] = '1';
  }

  return $e;
}

/**
 * Implements hook_token_info_alter().
 */
function zoetrope_viewer_token_info_alter(&$info) {
  $fields = field_info_fields();
  // Attach field tokens to their respecitve entity tokens.
  foreach ($fields as $field_name => $field) {

    if ($field['type'] == 'zoetrope_uuid_field') {
      foreach (array_keys($field['bundles']) as $token_type) {
        $token_name = $field_name . '_preview_url';
        $info['tokens'][$token_type][$token_name] = array(
          'name' => t('@field Preview url', array('@field' => $field_name)),
          'description' => t('The url of the preview jpg for an engage image'),
          'module' => 'zoetrope_viewer',
        );
      }
    }
  }

}

/**
 * Implements hook_tokens().
 */
function zoetrope_viewer_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  $sanitize = !empty($options['sanitize']);

  if ($type == 'entity' && !empty($data['entity_type']) && !empty($data['entity']) && !empty($data['token_type'])) {

    foreach ($tokens as $field_name_suffixed => $token) {

      if (isset($tokens[$field_name_suffixed]) && _token_module($data['token_type'], $field_name_suffixed) == 'zoetrope_viewer') {

        $field_name = str_replace('_preview_url', '', $field_name_suffixed);
        $entity = $data['entity'];
        $field_info = field_info_field($field_name);
        if ($field_info['type'] != 'zoetrope_uuid_field' || empty($entity->{$field_name})) {
          continue;
        }
        /*
         * TODO: How to deal with multiple deltas?
         */
        $url = zoetrope_viewer_preview_image_url($entity->{$field_name}[LANGUAGE_NONE][0]['zoetrope_uuid']);
        $replacements[$token] = $url;
      }
    }
  }

  return $replacements;
}

// Helper functions.
/**
 * Returns a preview image URL from the CDN.
 */
function _zoetrope_viewer_image_url($uuid, $size = 500, $position = 0, $cdn = FALSE) {
  $mode = !empty($_SERVER['HTTPS']) ? 'https:' : 'http:';
  if ($cdn == FALSE) {
    $cdn = variable_get('zoetrope_viewer:cdn', ZOETROPE_VIEWER_CDN);
  }
  if (!in_array($size, array(250, 500, 1000))) {
    watchdog('Zoetrope Viewer', 'Invalid image size `@size` selected for preview, should have been 250,500 or 1000.',
              array('@size' => $size), WATCHDOG_ERROR);
  }
  return $mode . $cdn . '/' . $uuid . '/' . $size . '/' . $position . '.jpg';
}

/**
 * Shortcut for `_zoetrope_viewer_image_url($uuid, 500, 0)`.
 */
function zoetrope_viewer_preview_image_url($uuid, $cdn=FALSE) {
  return _zoetrope_viewer_image_url($uuid, 500, 0, $cdn);
}

/**
 * Shortcut for `_zoetrope_viewer_image_url($uuid, 1000, 0)`.
 */
function zoetrope_viewer_large_image_url($uuid, $cdn=FALSE) {
  return _zoetrope_viewer_image_url($uuid, 1000, 0, $cdn);
}
